### ISSUE TITLE
Adding Dictionary object when sending custom Events are failing for Android

### ISSUE THREAD

**Issue by hawjefferson** [mParticle/mparticle-unity-plugin#9]
The Unity Android SDK wrapper is generating the following error if a dictionary object is passed as an argument when logging a custom Event.

 MParticle.Instance.LogEvent (new MPEvent("Browse Events", mParticle.EventType.Other) {
    	        Info = new Dictionary<string, string>{{ "Event", "Sporting Event" }, {"Start Date Range", "1/14"}, {"End Date Range", "5/14"}}
            }
            );
            MParticle.Instance.Upload();

03-24 22:12:17.400 32574 20430 E Unity   : AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='put' signature='([Ljava/lang/String;)V' in class Ljava.lang.Object;
03-24 22:12:17.400 32574 20430 E Unity   : java.lang.NoSuchMethodError: no non-static method with name='put' signature='([Ljava/lang/String;)V' in class Ljava.lang.Object;
03-24 22:12:17.400 32574 20430 E Unity   : 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:162)
03-24 22:12:17.400 32574 20430 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
03-24 22:12:17.400 32574 20430 E Unity   : 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
03-24 22:12:17.400 32574 20430 E Unity   : 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
03-24 22:12:17.400 32574 20430 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-24 22:12:17.400 32574 20430 E Unity   : 	at android.os.Looper.loop(Looper.java:246)
03-24 22:12:17.400 32574 20430 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
03-24 22:12:17.400 32574 20430 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x0003c] in <5ebb0610eb504545a903252b7d55fe06>:0 
03-24 22:12:17.400 32574 20430 E Unity   :   at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName, System.String si
03-24 22:12:17.401   552   552 I zygote  : Delayed USAP Pool refill. New USAPs: 1
03-24 22:12:17.411   975  1310 V WindowManager: Relayout Window{7ed495c u0 com.DefaultCompany.TestMParticle/com.unity3d.player.UnityPlayerActivity}: viewVisibility=0 req=1440x3040
03-24 22:12:17.413   975  1310 D PowerManagerService: [api] release WakeLock SCREEN_BRIGHT_WAKE_LOCK        'WindowManager' ON_AFTER_RELEASE ACQ=-2s789ms (uid=1000 pid=975 pkg=android ws=WorkSource{10600})
03-24 22:12:17.413   975  1714 W SensorService: sensor 00000001 already enabled in connection 0x7d3de81bf0 (ignoring)

**Comment by willpassidomo** [comment]
Hey @hawjefferson for reporting. This was indeed as issues and it has been fixed in [PR 10](https://github.com/mParticle/mparticle-unity-plugin/pull/10 and released in [v 3.3.1](https://github.com/mParticle/mparticle-unity-plugin/releases/tag/v3.3.1)
